# permissions for end users to view cloudhsms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudhsm-viewer-role
rules:
- apiGroups:
  - cloudhsm.hhamalai.net
  resources:
  - cloudhsms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudhsm.hhamalai.net
  resources:
  - cloudhsms/status
  verbs:
  - get
