
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cloudhsm.hhamalai.net
  resources:
  - cloudhsms
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudhsm.hhamalai.net
  resources:
  - cloudhsms/status
  verbs:
  - get
  - patch
  - update
