apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cloudhsms.cloudhsm.hhamalai.net
spec:
  group: cloudhsm.hhamalai.net
  names:
    kind: CloudHSM
    listKind: CloudHSMList
    plural: cloudhsms
    singular: cloudhsm
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CloudHSM is the Schema for the cloudhsms API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CloudHSMSpec defines the desired state of CloudHSM
          properties:
            size:
              description: 'Desired number of CloudHSM devices in cluster'
              format: int32
              type: integer
            clusterId:
              description 'CloudHSM cluster ID to manage'
              type: string
          required:
          - clusterId
          - size
          type: object
        status:
          description: CloudHSMStatus defines the observed state of CloudHSM
          properties:
            devices:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
          required:
          - devices
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
